### ISSUE TITLE
Output config file not appearing

### ISSUE THREAD

**Issue by gp1234** [gimoteco/gatsby-plugin-nginx-redirect#1]
Hello I am trying to use the plugin but for some reason the output file is remaining empty. Any idea what it could be?

**Comment by gp1234** [comment]
After some trial and error I changed to onPreBuild and it worked, but conf.nginx.server._add is undefined ( I am using this example nginx config https://github.com/tmont/nginx-conf/blob/master/tests/files/nginx-home.conf). I can however use conf.nginx.http.server, I am not very savy in servers matter and I dont know if this is going to work. Thank you for your time!

**Comment by gimoteco** [comment]
I don't have any idea of what was happening with you, could you share your gatsby-config (only this plugin part) and gatsby version? Just to make clear you must have an input file like this one:
```
server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
    location = /50x.html {
        root /usr/share/nginx/html;
    }
    error_page 500 502 503 504  /50x.html;
}
```

and this plugin will add 
the rewrites
```
server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
    location = /50x.html {
        root /usr/share/nginx/html;
    }
    error_page 500 502 503 504  /50x.html;
    rewrite ^/from\/?$ /to permanent;
```

**Comment by gp1234** [comment]
Hello, I am so sorry to the last response. I have downloaded an minimal starter gatsby site to make the test [Gatsby starter](https://www.gatsbyjs.org/starters/gatsbyjs/gatsby-starter-default/). Then I proceed to install the plugin, set the configuration as in the documentation, write the redirect in gatsby node and the use the entry config file you have put. When I run the command gatsby build it dont throw any errors but the new config file dont appear anywhere. Any ideas?

**Comment by daydream05** [comment]
I'm having a similar issue here's my gatsby-config

```
    {
      resolve: "gatsby-plugin-nginx-redirect",
      options: {
        inputConfigFile: `${__dirname}/nginx.conf`,
        outputConfigFile: `${__dirname}/nginx.out.conf`,
      },
    },
```

**Comment by gimoteco** [comment]
First of all, thank you for reporting the problem. I checked here on another machine and the bug really happens. It seems caused by some nginx sync issue, I added some sleeps to guarantee file synchronization. I hope this fix for you. Please check the version 0.0.9.
